In [5]:
import sys, os 
import pandas as pd 
import numpy as np
import utils

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import precision_recall_fscore_support, classification_report, accuracy_score
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
def load_data():

    data = os.path.join("data", "train.csv")

    df = pd.read_csv(data)
    X_train = df[['id', 'comment_text']]
    y_train = df[['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']]

    X_test = pd.read_csv(os.path.join("data", "test.csv"))
    y_test = pd.read_csv(os.path.join("data", "test_labels.csv"))
    test = X_test.merge(y_test, on='id')
    test = test[ (test['toxic']!=-1) | (test['severe_toxic']!=-1) | 
                (test['obscene']!=-1) | (test['threat']!=-1) | (test['insult']!=-1) 
                | (test['identity_hate']!=-1) ]
    test = test.reset_index(drop=True) 
    
    X_test = test[['id', 'comment_text']]
    y_test = test[['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']]

    return X_train, y_train, X_test, y_test 

In [7]:
# Constants 

ngrams = 1
penalty = 'l2'
Cs = 10
cv = 5
max_iter = 1000 
scoring = 'accuracy'

In [53]:
X_train, y_train, X_test, y_test = utils.load_data()
np.random.seed(42)

In [54]:
X_train

id                                       comment_text
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...
5       00025465d4725e87  "\n\nCongratulations from me as well, use the ...
6       0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK
7       00031b1e95af7921  Your vandalism to the Matt Shirvington article...
8       00037261f536c51d  Sorry if the word 'nonsense' was offensive to ...
9       00040093b2687caa  alignment on this subject and which are contra...
10      0005300084f90edc  "\nFair use rationale for Image:Wonju.jpg\n\nT...
11      00054a5e18b50dd4  bbq \n\nbe a man and lets discuss it-maybe ove...
12      0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......
13      0006f16e4e9f292e  Before you start throwing accusations and warn...
14      00070ef96486d6f9  Oh, and the girl above started her arguments w...
15      00078f8ce7eb276d  "\n\nJuelz Santanas Age\n\nIn 2002, Juelz Sant...
16      0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...
17      000897889268bc93   REDIRECT Talk:Voydan Pop Georgiev- Chernodrinski
18      0009801bd85e5806  The Mitsurugi point made no sense - why not ar...
19      0009eaea3325de8c  Don't mean to bother you \n\nI see that you're...
20      000b08c464718505  "\n\n Regarding your recent edits \n\nOnce aga...
21      000bfd0867774845  "\nGood to know. About me, yeah, I'm studying ...
22      000c0dfd995809fa  "\n\n Snowflakes are NOT always symmetrical! \...
23      000c6a3f0cd3ba8e  "\n\n The Signpost: 24 September 2012 \n\n Rea...
24      000cfee90f50d471  "\n\nRe-considering 1st paragraph edit?\nI don...
25      000eefc67a2c930f  Radial symmetry \n\nSeveral now extinct lineag...
26      000f35deef84dc4a  There's no need to apologize. A Wikipedia arti...
27      000ffab30195c5e1  Yes, because the mother of the child in the ca...
28      0010307a3a50a353  "\nOk. But it will take a bit of work but I ca...
29      0010833a96e1f886  "== A barnstar for you! ==\n\n  The Real Life ...
...                  ...                                                ...
159541  ffa33d3122b599d6  Your absurd edits \n\nYour absurd edits on gre...
159542  ffa95244f261527f  maybe he's got better things to do than spend ...
159543  ffad104337fe9891  scrap that, it does meet criteria and its gone...
159544  ffaed63c487a2b42                                You could do worse.
159545  ffb268f37788a011  , 7 March 2011 (UTC)\nAre you also User:Bmatts...
159546  ffb47123b2d82762  "\n\nHey listen don't you ever!!!! Delete my e...
159547  ffb7b4c3d3ae5842                     Thank you very, very much.  ·✆
159548  ffb93b0a0a1e78f9                        Talkback: 15 September 2012
159549  ffb998f9749bd83e                         2005 (UTC)\n 06:35, 31 Mar
159550  ffba5332d6b8fd14  i agree/ on another note lil wayne is a talent...
159551  ffbc2db4225258dd  While about half the references are from BYU-I...
159552  ffbcd64a71775e04  Prague Spring \n\nI think that Prague Spring d...
159553  ffbd331a3aa269b9  I see this as having been merged; undoing one ...
159554  ffbdbb0483ed0841  and i'm going to keep posting the stuff u dele...
159555  ffc2f409658571f1  "\n\nHow come when you download that MP3 it's ...
159556  ffc671f2acdd80e1  I'll be on IRC, too, if you have a more specif...
159557  ffc7bbb177c3c966  It is my opinion that that happens to be off-t...
159558  ffca1e81aefc48ac  Please stop removing content from Wikipedia; i...
159559  ffca8d71d71a3fae  Image:Barack-obama-mother.jpg listed for delet...
159560  ffcdcb71854f6d8a  "Editing of article without Consensus & Remova...
159561  ffd2e85b07b3c7e4  "\nNo he did not, read it again (I would hav

In [9]:
vectorizer = TfidfVectorizer(ngram_range=(1, ngrams))

In [10]:
def tfidf_transform(corpus, is_train=False):
    if is_train: 
        X = vectorizer.fit_transform(corpus)
    else:
        X = vectorizer.transform(corpus)
    return X

In [11]:
def print_results(model, X, y):
    """
    Evaluate the model, prints results, and return as tuple
    """
    prediction = model.predict(X)
    precision, recall, fbeta_score, support = \
        precision_recall_fscore_support(y, prediction)
    accuracy = accuracy_score(y, prediction)

    print ("Precision: {}\nRecall: {}\nF-Score: {}\nSupport: {}\nAccuracy {}\n".format(
            precision, recall, fbeta_score, support, accuracy))

    print (classification_report(y, prediction))

    return (precision, recall, fbeta_score, support, accuracy)

In [12]:
# turn the corpus into a list to pass into the vectorizer 
train_corpus = X_train['comment_text'].values.tolist()
test_corpus = X_test['comment_text'].values.tolist()

X_train_tfidf = tfidf_transform(train_corpus, is_train=True)
X_test_tfidf = tfidf_transform(test_corpus, is_train=False)

In [13]:
def run_model(): 
    labels = ['toxic' , 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']
    
    for label in labels: 
        print("Train model on the \"{}\" label.\n".format(label))
        y_train_label = y_train[label].values.tolist()
        y_test_label = y_test[label].values.tolist()
        
        lr = LogisticRegressionCV(   class_weight="balanced", 
                                     Cs = Cs, 
                                     cv = cv, 
                                     penalty = penalty, 
                                     scoring = scoring, 
                                     max_iter = max_iter)
        
        lr.fit(X_train_tfidf, y_train_label)
        
        print("Train Results\n")
        print_results(lr, X_train_tfidf, y_train_label)
        
        print("Test Results\n")
        
        print_results(lr, X_test_tfidf, y_test_label)

In [14]:
run_model()

Train model on the "toxic" label.



/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Incre

Train Results

Precision: [0.99978171 0.86943891]
Recall: [0.98411389 0.99797306]
F-Score: [0.99188594 0.92928247]
Support: [144277  15294]
Accuracy 0.9854422169441815

              precision    recall  f1-score   support

           0       1.00      0.98      0.99    144277
           1       0.87      1.00      0.93     15294

   micro avg       0.99      0.99      0.99    159571
   macro avg       0.93      0.99      0.96    159571
weighted avg       0.99      0.99      0.99    159571

Example predictions: 
[0 0 0 ... 0 0 0]
Test Results

Precision: [0.98559356 0.48064953]
Recall: [0.90054934 0.87487685]
F-Score: [0.94115417 0.62043668]
Support: [57888  6090]
Accuracy 0.8981055987995874

              precision    recall  f1-score   support

           0       0.99      0.90      0.94     57888
           1       0.48      0.87      0.62      6090

   micro avg       0.90      0.90      0.90     63978
   macro avg       0.73      0.89      0.78     63978
weighted avg       0.94   

/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Incre

Train Results

Precision: [0.99999362 0.56464754]
Recall: [0.99222034 0.99937304]
F-Score: [0.99609181 0.72159348]
Support: [157976   1595]
Accuracy 0.9922918324758258

              precision    recall  f1-score   support

           0       1.00      0.99      1.00    157976
           1       0.56      1.00      0.72      1595

   micro avg       0.99      0.99      0.99    159571
   macro avg       0.78      1.00      0.86    159571
weighted avg       1.00      0.99      0.99    159571

Example predictions: 
[0 0 0 ... 0 0 0]
Test Results

Precision: [0.99852706 0.18115942]
Recall: [0.98045935 0.7493188 ]
F-Score: [0.98941073 0.29177719]
Support: [63611   367]
Accuracy 0.9791334521241677

              precision    recall  f1-score   support

           0       1.00      0.98      0.99     63611
           1       0.18      0.75      0.29       367

   micro avg       0.98      0.98      0.98     63978
   macro avg       0.59      0.86      0.64     63978
weighted avg       0.99   

/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Incre

Train Results

Precision: [0.99996    0.88297427]
Recall: [0.99259539 0.99928986]
F-Score: [0.99626408 0.93753817]
Support: [151122   8449]
Accuracy 0.99294984677667

              precision    recall  f1-score   support

           0       1.00      0.99      1.00    151122
           1       0.88      1.00      0.94      8449

   micro avg       0.99      0.99      0.99    159571
   macro avg       0.94      1.00      0.97    159571
weighted avg       0.99      0.99      0.99    159571

Example predictions: 
[0 0 0 ... 0 0 0]
Test Results

Precision: [0.98870182 0.53663717]
Recall: [0.95657439 0.8214576 ]
F-Score: [0.9723728  0.64918103]
Support: [60287  3691]
Accuracy 0.9487792678733314

              precision    recall  f1-score   support

           0       0.99      0.96      0.97     60287
           1       0.54      0.82      0.65      3691

   micro avg       0.95      0.95      0.95     63978
   macro avg       0.76      0.89      0.81     63978
weighted avg       0.96     

/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Incre

Train Results

Precision: [0.99996659 0.79434914]
Recall: [0.98656506 0.99936524]
F-Score: [0.99322062 0.88514083]
Support: [151694   7877]
Accuracy 0.9871969217464326

              precision    recall  f1-score   support

           0       1.00      0.99      0.99    151694
           1       0.79      1.00      0.89      7877

   micro avg       0.99      0.99      0.99    159571
   macro avg       0.90      0.99      0.94    159571
weighted avg       0.99      0.99      0.99    159571

Example predictions: 
[0 0 0 ... 0 0 0]
Test Results

Precision: [0.9861626  0.48097776]
Recall: [0.95336163 0.76364167]
F-Score: [0.96948475 0.590212  ]
Support: [60551  3427]
Accuracy 0.9431992247335022

              precision    recall  f1-score   support

           0       0.99      0.95      0.97     60551
           1       0.48      0.76      0.59      3427

   micro avg       0.94      0.94      0.94     63978
   macro avg       0.73      0.86      0.78     63978
weighted avg       0.96   

/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/guywuollet/anaconda/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Incre

Train Results

Precision: [0.9999873  0.65560748]
Recall: [0.99534034 0.99857651]
F-Score: [0.99765841 0.79153738]
Support: [158166   1405]
Accuracy 0.9953688326826303

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    158166
           1       0.66      1.00      0.79      1405

   micro avg       1.00      1.00      1.00    159571
   macro avg       0.83      1.00      0.89    159571
weighted avg       1.00      1.00      1.00    159571

Example predictions: 
[0 0 0 ... 0 0 0]
Test Results

Precision: [0.99624433 0.33926031]
Recall: [0.98531597 0.66994382]
F-Score: [0.99075001 0.45042493]
Support: [63266   712]
Accuracy 0.9818062458970271

              precision    recall  f1-score   support

           0       1.00      0.99      0.99     63266
           1       0.34      0.67      0.45       712

   micro avg       0.98      0.98      0.98     63978
   macro avg       0.67      0.83      0.72     63978
weighted avg       0.99   

body  \
3926618  If you think you're crazy can you take your ow...   
565667                            >Klan meetings\n\nNAMBLA   
1708989  If you are moving at a constant speed, the air...   
2980595  Turns out the dish fairy is a drug addict . No...   
4558                  Oh wow i'd suck on that pussy good.    
3853867  Kinda but you can objectively say that you can...   
986535   Isn't the point of this sub to attention whore...   
409808                          You're full of shit! GTFO!   
2216616  I said in another thread, he could win 4 more ...   
1076143  Paige vs Michelle is a lose lose for all fight...   
3167827                        Can you be my night nurse?    
2955245                 People need to learn how to edit.    
2790515                I can hear the blades swooshing now   
2899642  You take a lot of a id and id not talk about i...   
3929983  MEGAN ANDERSON IS A ONCE IN A LIFETIME ATHLETE...   
3923006  Oh damn in that case that's on him. My bad for...   
1934619  Dude, even they couldnt find a crime she comit...   
2039354                               And rightly so pede!   
2734128  Dubs fans are complaining in another thread ab...   
1423757            i don't want a fall guy. I WANT HILLARY   
567072                              Happy wife, happy life   
1605230                                       Bad decision   
3367327  In his final season? Yeah. In the classroom an...   
1667898  What kind of toys i should buy for my kid is y...   
2353284  I had the same thing happen to me! Hospitalize...   
1684201  Let's hope for the best. The best naming she d...   
878490                                        Vote shaming   
1647657  Anyone calling Islam the religion of peace is ...   
2639969  Your a prime example of someone who puts their...   
1375800  When I read steam reviews I always go for the ...   
...                                                    ...   
3381524                                             Yes :(   
103355                                          Who's Rem?   
791743   Remember that he is raising the question AFTER...   
3344769                        *Five years of art school!*   
1825573  Of course there is something wrong with being ...   
327069   You calling all the veterans that came out to ...   
1766891  >Sometime soon I am going to suggest that Bern...   
1370455         You're on FL. What do you honestly expect?   
787201   Trump graduated from the top business school i...   
3210548  They didn’t mention the underwear, except by u...   
329365   She is hot and Donald Trump is a terrible pres...   
2138242  2 weeks ago, I was in LFR with my 895 rogue fr...   
278167                                       what the fuck   
1239911  Would this move Earths trajectory a tiny fract...   
2272355  I played a ton of Call of Duty, but gave it up...   
3009908                                           The refs   
1136074  > You lost.\n\nI have no horses in this race, ...   
2003274  Hi /u/Versaiii,\n\nIt looks like you haven't a...   
1570006                        OK mate try to fix stream 1   
3097042  2020 nuclear disarmament date. Did you want NK...   
2234489  She absolutely uses Verizon's official support...   
3200614        Catira?\n\nI'm fully invested into this lol   
732180   1-800-SUICIDE\n\nPlease give them a call - you...   
110268   You'll be fine. In the future keep an eye out ...   
1692743  Hi washheightsboy3 thank you for submitting to...   
2356330  Trump was President for 8ish months at that ti...   
3511566                                              Nice.   
2229084  What? This is excellent news towards deescalat...   
2768307  Serious question from a non American, is priso...   
2219110  i had a slight heart attack when he said he pa...   

                   subreddit  
3926618            AskReddit  
565667              politics  
1708989           askscience  
2980595            AskReddit  
4558                gonewild  
3853867          hiphop